### ISSUE TITLE
Contour detection: show circle `(x, y, r)` and ellipse `(x, y, a, b, theta)` instead of `(x0, y0, x1, x1, ...)`

### ISSUE THREAD

**Issue by emarin2642** [Codra-Ingenierie-Informatique/DataLab#32]
**Describe the bug**
For the circle contour detection, the results are very bad as you see on the first image. The detection gives some results outside of the ROI !
I want also to point out that the contour shape parameters are sometimes impossible to read due to the bad contrast.

When we use the ellipse contour detection, the results are really good (see second image) but it will be more interesting to give the ellipse parameters (size of the two axes and the inclination) instead of the coordinates of 4 points.
 
![Detection_taille_anneau](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/156417789/2c218c57-9998-4bbb-b4c7-03d966f7d9cc)
![Ellipse_detection](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/156417789/571ebd45-73e4-4eb4-b029-5e354a513df6)

**Comment by PierreRaybaut** [comment]
If you could share your image, it would be great.
When generating a simple ring on an image, both the contour detection works fine with both "circle" and "ellipse" parameters.

**Comment by emarin2642** [comment]
Please find the image used.
![Fig_LongI=0](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/156417789/aa2ddb76-525b-4c75-8d3c-58817f0925c3)
![Fig_LongI=3](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/156417789/21cf9bb0-0487-4bd8-b1cf-64454ef09f1b)

**Comment by PierreRaybaut** [comment]
It's always interesting to have different kind of data because depending on the source of the data, the algorithms sometimes behaves unexpectedly. That is the case with your images (plus a couple of bugs which are highlighted by manipulating those images in the meantime...).

Would you agree if those images were added to the test data of DataLab source package?

**Comment by PierreRaybaut** [comment]
These images look like Fabry-Perot fringes... but maybe this has nothing to do with it?
(I originally am an optical engineer)

**Comment by emarin2642** [comment]
Of course you can used and add these images for the test data. 
You are also right these are Fabry-Perot fringes that we obtain during the lab focus on Zeemann Effect. My first idea was to install and use DataLab, during the lab,  to determine the ring radius. However, now this is not so evident for me!

**Comment by PierreRaybaut** [comment]
(Sorry, closed the wrong issue)

**Comment by emarin2642** [comment]
It is exactly what I want but I don't find the way to install this new version ;)

**Comment by PierreRaybaut** [comment]
FYI, in the latest release:

![image](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/1311787/b1eeab78-2fb4-4329-8ca4-8b864c8886f6)

**Comment by PierreRaybaut** [comment]
@emarin2642 : a new tutorial is available around this topic (in both [english](https://codra-ingenierie-informatique.github.io/DataLab/en/intro/tutorials/fabry_perot.html) and [french](https://codra-ingenierie-informatique.github.io/DataLab/fr/intro/tutorials/fabry_perot.html))

**Comment by emarin2642** [comment]
Bonjour,
Très très interessant et c’est très bien que le tuto soit dans les deux car
j’ai des étudiants étrangers.
Je regarde actuellement pour utiliser l’application pour un TP laser pour
déterminer la taille des modes.
Quelques remarques rapides
Dans la fenêtre des calculs à quoi sert le bouton ‘apply’ car on peut
l’utiliser qu’une fois !!!
Quand on édit des  meta-donnees impossible de sélectionner celle que l’on
voudrait copier !!
Merci en tout cas pour votre réactivité.
Des que j’ai des images de modes laser je vous les envoie.
Cdt


Le ven. 19 janv. 2024 à 18:33, Pierre Raybaut ***@***.***> a
écrit :

**Comment by PierreRaybaut** [comment]
_(I'm translating your previous post in english so that other people may benefit from it, eventually)_
> "Hello,
> Very, very interesting and it's great that the tutorial is in both languages because
> I have foreign students.
> I am currently looking to use the application for a laser practical work to
> determine the size of the modes.
> A few quick remarks:
> In the calculation window, what is the purpose of the 'apply' button since it can
> only be used once!!!

I suppose that you are referring to this "Apply" button:
![image](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/1311787/54622651-f0b5-4ed0-9329-b20e55165b51)

It may be confusing that the button is placed on the same GUI layout as the rest of the editable forms and buttons (which are clearly related to Image/Signal properties). Actually, the purpose of this "Apply" button is to validate the changes that are made in the forms above (e.g. title of axes, units, ...). That's why it's greyed out after pushing it: it should be enabled again after changing any value in the fields above.

I've just committed a change that may clarify this: the button is now disabled by default (this is new), and then enabled only when a property is changed (this was already implemented).

> When editing metadata, it's impossible to select the one you would like to copy!!

In the metadata editor dialog, when you right-click on an entry, the context menu allows to copy data:
(is it what you were looking for?)

![image](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/1311787/ba16a98d-0f9a-4f1f-9a8e-88212f2e9683)

> Thank you anyway for your responsiveness.

Thanks for sharing your thoughts on DataLab (and some data as well!).

> As soon as I have images of laser modes, I will send them to you.

Please do not hesitate to send them, indeed.
