### ISSUE TITLE
Error when trying to open a (UTF-8 BOM) text file as an image

### ISSUE THREAD

**Issue by emarin2642** [Codra-Ingenierie-Informatique/DataLab#49]
Hello,
I have issues when open either signals or images in text format (csv or txt). 
The issues are quite simple because it is simply an error message without any import.
The file used is attached
E.M.
[potentiel_condensateur_2.csv](https://github.com/Codra-Ingenierie-Informatique/DataLab/files/14181892/potentiel_condensateur_2.csv)

**Comment by PierreRaybaut** [comment]
Yes, trying to open this file from the **Signal Panel** would lead to:

![image](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/1311787/341f03ea-4ff8-432c-a1fe-31da60027f03)

Actually, from a certain point of view, that is the expected behavior because - as implied in the dialog box above - the data sets must have 2, 3 or 4 columns:

- 2 columns are interpreted as: x, y
- 3 columns are interpreted as: x, y, dy
- 4 columns are interpreted as: x, y, dx, dy

To be able to open arbitrary text files, we would have to implement something like the data import wizard in Spyder:

![image](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/1311787/9a958745-41e1-497e-a8be-505a1961395e)

So that would be a feature request... but a very interesting one indeed!

**Comment by PierreRaybaut** [comment]
> In the meantime, I think that we could try to transpose the data before throwing this error message.

Actually, my mistake: it's currently not possible to create multiple signals from one text file.
The import wizard will take care of this too.

In the meantime, when opening this kind of text file, we could simple ask the user about what will be considered as curve data (rows or columns).

**Comment by emarin2642** [comment]
Thank you for your responses.
My first goal was to test the representation like an image because these data are the potential measured at different locations in the horizontal plane. The potential is created by a dipole. The idea is to put in evidence the equipotentials (see the image attached) for the students during a lab.
![Equipotential](https://github.com/Codra-Ingenierie-Informatique/DataLab/assets/156417789/00f004e1-7158-4513-985c-04dbd93b9757)
